---
abstract: 'Interactively prompt user to generate a config module'
author:
  - 'Joshua Keroes <joshua@cpan.org>'
build_requires:
  Test::More: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-TestConfig
requires:
  Carp: 0
  Config::Auto: 0
  Data::Dumper: 0
  Fcntl: 0
  File::Basename: 0
  File::Path: 0
  Params::Validate: 0
  Term::ReadKey: 0
  Text::FormatTable: 0
  perl: 5.008
  strict: 0
  warnings: 0
version: 0.06_01
