# -*- perl -*-
#
# This module was autogenerated by Module::TestConfig

package MyConfig;

use strict;
use Carp;
use vars '$AUTOLOAD';

sub new {
    my $proto = shift;
    my $class = ref $proto || $proto;
    my $self = {
          'one' => 1,
          'three' => 3,
          'two' => 2,
          'four' => 4,
          'testconfig_five' => 5
        }
;
    return bless $self, $class;
}

sub AUTOLOAD {
    my $self = shift;

    ($AUTOLOAD) = $AUTOLOAD =~ /(\w+)$/;

    croak "No such method: $AUTOLOAD"
        unless defined $self->{$AUTOLOAD}
            || $AUTOLOAD eq "DESTROY";

    return $self->{$AUTOLOAD};
}

1;
